project:
  type: manuscript
  
manuscript:
  article: index.qmd
  notebooks: 
    - notebook: notebooks/explorare.qmd
      title: Exlorarea Datelor
  code-links: 
    - text: Source Code
      href : https://github.com/buciupetre2020/UBBCluj_chapter

format:
  html:
    comments:
      hypothesis: true
    toc: true
    toc-location: left
    toc-title: Cuprins
    abstract-title: Abstract
    theme: lumen
  docx: default

  # (other formats)
  # pdf: default

execute:
  freeze: auto



