project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  
  # (other formats)
  # pdf: default

execute:
  freeze: true



